coverage:
    status:
      project:
        default:
          # basic
          target: auto
          threshold: 1%
          base: auto
          if_not_found: success
          if_ci_failed: error
          informational: false
          only_pulls: true
